### ISSUE TITLE
SAN certificate support

### ISSUE THREAD

**Issue by klehmann** [zero11it/acme-client#2]
Is there a way to request SAN certificates with the acme-client or is it already a planned feature?

**Comment by davidef** [comment]
I'm planning to do some development during the Christmas holidays but feel free to implement it and make a pull request

**Comment by davidef** [comment]
It was easier than expected. I've just push the 0.1.2 version with SAN support (some interfaces changed in order to support multiple domains)

**Comment by klehmann** [comment]
Thanks a lot! Will test it.

**Comment by klehmann** [comment]
Had time to test it. It's working for me. Very cool!
